// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: cart/v1/cart.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AddCartRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddCartRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddCartRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddCartRequestMultiError,
// or nil if none found.
func (m *AddCartRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddCartRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if wrapper := m.GetUserId(); wrapper != nil {

		if wrapper.GetValue() <= 0 {
			err := AddCartRequestValidationError{
				field:  "UserId",
				reason: "value must be greater than 0",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	} else {
		err := AddCartRequestValidationError{
			field:  "UserId",
			reason: "value is required and must not be nil.",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if wrapper := m.GetGoodsId(); wrapper != nil {

		if wrapper.GetValue() <= 0 {
			err := AddCartRequestValidationError{
				field:  "GoodsId",
				reason: "value must be greater than 0",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	} else {
		err := AddCartRequestValidationError{
			field:  "GoodsId",
			reason: "value is required and must not be nil.",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if wrapper := m.GetGoodsSku(); wrapper != nil {

		if wrapper.GetValue() <= 0 {
			err := AddCartRequestValidationError{
				field:  "GoodsSku",
				reason: "value must be greater than 0",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	} else {
		err := AddCartRequestValidationError{
			field:  "GoodsSku",
			reason: "value is required and must not be nil.",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AddCartRequestMultiError(errors)
	}

	return nil
}

// AddCartRequestMultiError is an error wrapping multiple validation errors
// returned by AddCartRequest.ValidateAll() if the designated constraints
// aren't met.
type AddCartRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddCartRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddCartRequestMultiError) AllErrors() []error { return m }

// AddCartRequestValidationError is the validation error returned by
// AddCartRequest.Validate if the designated constraints aren't met.
type AddCartRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddCartRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddCartRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddCartRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddCartRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddCartRequestValidationError) ErrorName() string { return "AddCartRequestValidationError" }

// Error satisfies the builtin error interface
func (e AddCartRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddCartRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddCartRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddCartRequestValidationError{}

// Validate checks the field values on Cart with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Cart) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Cart with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in CartMultiError, or nil if none found.
func (m *Cart) ValidateAll() error {
	return m.validate(true)
}

func (m *Cart) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for GoodsId

	// no validation rules for GoodsSku

	// no validation rules for Num

	if len(errors) > 0 {
		return CartMultiError(errors)
	}

	return nil
}

// CartMultiError is an error wrapping multiple validation errors returned by
// Cart.ValidateAll() if the designated constraints aren't met.
type CartMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CartMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CartMultiError) AllErrors() []error { return m }

// CartValidationError is the validation error returned by Cart.Validate if the
// designated constraints aren't met.
type CartValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CartValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CartValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CartValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CartValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CartValidationError) ErrorName() string { return "CartValidationError" }

// Error satisfies the builtin error interface
func (e CartValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCart.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CartValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CartValidationError{}

// Validate checks the field values on AddCartReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddCartReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddCartReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddCartReplyMultiError, or
// nil if none found.
func (m *AddCartReply) ValidateAll() error {
	return m.validate(true)
}

func (m *AddCartReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCart()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AddCartReplyValidationError{
					field:  "Cart",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AddCartReplyValidationError{
					field:  "Cart",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCart()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AddCartReplyValidationError{
				field:  "Cart",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AddCartReplyMultiError(errors)
	}

	return nil
}

// AddCartReplyMultiError is an error wrapping multiple validation errors
// returned by AddCartReply.ValidateAll() if the designated constraints aren't met.
type AddCartReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddCartReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddCartReplyMultiError) AllErrors() []error { return m }

// AddCartReplyValidationError is the validation error returned by
// AddCartReply.Validate if the designated constraints aren't met.
type AddCartReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddCartReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddCartReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddCartReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddCartReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddCartReplyValidationError) ErrorName() string { return "AddCartReplyValidationError" }

// Error satisfies the builtin error interface
func (e AddCartReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddCartReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddCartReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddCartReplyValidationError{}
