// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: cart/v1/cart.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AddCartRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddCartRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddCartRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddCartRequestMultiError,
// or nil if none found.
func (m *AddCartRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddCartRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if wrapper := m.GetUserId(); wrapper != nil {

		if wrapper.GetValue() <= 0 {
			err := AddCartRequestValidationError{
				field:  "UserId",
				reason: "value must be greater than 0",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	} else {
		err := AddCartRequestValidationError{
			field:  "UserId",
			reason: "value is required and must not be nil.",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if wrapper := m.GetGoodsId(); wrapper != nil {

		if wrapper.GetValue() <= 0 {
			err := AddCartRequestValidationError{
				field:  "GoodsId",
				reason: "value must be greater than 0",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	} else {
		err := AddCartRequestValidationError{
			field:  "GoodsId",
			reason: "value is required and must not be nil.",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if wrapper := m.GetGoodsSkuId(); wrapper != nil {

		if wrapper.GetValue() <= 0 {
			err := AddCartRequestValidationError{
				field:  "GoodsSkuId",
				reason: "value must be greater than 0",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	} else {
		err := AddCartRequestValidationError{
			field:  "GoodsSkuId",
			reason: "value is required and must not be nil.",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetGoodsSkuDesc()); l < 1 || l > 50 {
		err := AddCartRequestValidationError{
			field:  "GoodsSkuDesc",
			reason: "value length must be between 1 and 50 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AddCartRequestMultiError(errors)
	}

	return nil
}

// AddCartRequestMultiError is an error wrapping multiple validation errors
// returned by AddCartRequest.ValidateAll() if the designated constraints
// aren't met.
type AddCartRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddCartRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddCartRequestMultiError) AllErrors() []error { return m }

// AddCartRequestValidationError is the validation error returned by
// AddCartRequest.Validate if the designated constraints aren't met.
type AddCartRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddCartRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddCartRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddCartRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddCartRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddCartRequestValidationError) ErrorName() string { return "AddCartRequestValidationError" }

// Error satisfies the builtin error interface
func (e AddCartRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddCartRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddCartRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddCartRequestValidationError{}

// Validate checks the field values on Cart with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Cart) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Cart with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in CartMultiError, or nil if none found.
func (m *Cart) ValidateAll() error {
	return m.validate(true)
}

func (m *Cart) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for GoodsId

	// no validation rules for GoodsSkuId

	// no validation rules for GoodsSkuDesc

	// no validation rules for Num

	if len(errors) > 0 {
		return CartMultiError(errors)
	}

	return nil
}

// CartMultiError is an error wrapping multiple validation errors returned by
// Cart.ValidateAll() if the designated constraints aren't met.
type CartMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CartMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CartMultiError) AllErrors() []error { return m }

// CartValidationError is the validation error returned by Cart.Validate if the
// designated constraints aren't met.
type CartValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CartValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CartValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CartValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CartValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CartValidationError) ErrorName() string { return "CartValidationError" }

// Error satisfies the builtin error interface
func (e CartValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCart.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CartValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CartValidationError{}

// Validate checks the field values on AddCartReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddCartReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddCartReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddCartReplyMultiError, or
// nil if none found.
func (m *AddCartReply) ValidateAll() error {
	return m.validate(true)
}

func (m *AddCartReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCart()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AddCartReplyValidationError{
					field:  "Cart",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AddCartReplyValidationError{
					field:  "Cart",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCart()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AddCartReplyValidationError{
				field:  "Cart",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AddCartReplyMultiError(errors)
	}

	return nil
}

// AddCartReplyMultiError is an error wrapping multiple validation errors
// returned by AddCartReply.ValidateAll() if the designated constraints aren't met.
type AddCartReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddCartReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddCartReplyMultiError) AllErrors() []error { return m }

// AddCartReplyValidationError is the validation error returned by
// AddCartReply.Validate if the designated constraints aren't met.
type AddCartReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddCartReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddCartReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddCartReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddCartReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddCartReplyValidationError) ErrorName() string { return "AddCartReplyValidationError" }

// Error satisfies the builtin error interface
func (e AddCartReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddCartReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddCartReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddCartReplyValidationError{}

// Validate checks the field values on GetCartsByUserIdRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCartsByUserIdRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCartsByUserIdRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCartsByUserIdRequestMultiError, or nil if none found.
func (m *GetCartsByUserIdRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCartsByUserIdRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if wrapper := m.GetUserId(); wrapper != nil {

		if wrapper.GetValue() <= 0 {
			err := GetCartsByUserIdRequestValidationError{
				field:  "UserId",
				reason: "value must be greater than 0",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	} else {
		err := GetCartsByUserIdRequestValidationError{
			field:  "UserId",
			reason: "value is required and must not be nil.",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetCartsByUserIdRequestMultiError(errors)
	}

	return nil
}

// GetCartsByUserIdRequestMultiError is an error wrapping multiple validation
// errors returned by GetCartsByUserIdRequest.ValidateAll() if the designated
// constraints aren't met.
type GetCartsByUserIdRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCartsByUserIdRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCartsByUserIdRequestMultiError) AllErrors() []error { return m }

// GetCartsByUserIdRequestValidationError is the validation error returned by
// GetCartsByUserIdRequest.Validate if the designated constraints aren't met.
type GetCartsByUserIdRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCartsByUserIdRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCartsByUserIdRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCartsByUserIdRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCartsByUserIdRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCartsByUserIdRequestValidationError) ErrorName() string {
	return "GetCartsByUserIdRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetCartsByUserIdRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCartsByUserIdRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCartsByUserIdRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCartsByUserIdRequestValidationError{}

// Validate checks the field values on GetCartsByUserIdReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCartsByUserIdReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCartsByUserIdReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCartsByUserIdReplyMultiError, or nil if none found.
func (m *GetCartsByUserIdReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCartsByUserIdReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetCartsByUserIdReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetCartsByUserIdReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetCartsByUserIdReplyValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetCartsByUserIdReplyMultiError(errors)
	}

	return nil
}

// GetCartsByUserIdReplyMultiError is an error wrapping multiple validation
// errors returned by GetCartsByUserIdReply.ValidateAll() if the designated
// constraints aren't met.
type GetCartsByUserIdReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCartsByUserIdReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCartsByUserIdReplyMultiError) AllErrors() []error { return m }

// GetCartsByUserIdReplyValidationError is the validation error returned by
// GetCartsByUserIdReply.Validate if the designated constraints aren't met.
type GetCartsByUserIdReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCartsByUserIdReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCartsByUserIdReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCartsByUserIdReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCartsByUserIdReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCartsByUserIdReplyValidationError) ErrorName() string {
	return "GetCartsByUserIdReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetCartsByUserIdReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCartsByUserIdReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCartsByUserIdReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCartsByUserIdReplyValidationError{}

// Validate checks the field values on UpdateCartNumRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateCartNumRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateCartNumRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateCartNumRequestMultiError, or nil if none found.
func (m *UpdateCartNumRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateCartNumRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if wrapper := m.GetUserId(); wrapper != nil {

		if wrapper.GetValue() <= 0 {
			err := UpdateCartNumRequestValidationError{
				field:  "UserId",
				reason: "value must be greater than 0",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	} else {
		err := UpdateCartNumRequestValidationError{
			field:  "UserId",
			reason: "value is required and must not be nil.",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if wrapper := m.GetCartId(); wrapper != nil {

		if wrapper.GetValue() <= 0 {
			err := UpdateCartNumRequestValidationError{
				field:  "CartId",
				reason: "value must be greater than 0",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	} else {
		err := UpdateCartNumRequestValidationError{
			field:  "CartId",
			reason: "value is required and must not be nil.",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if wrapper := m.GetNum(); wrapper != nil {

		if wrapper.GetValue() <= 0 {
			err := UpdateCartNumRequestValidationError{
				field:  "Num",
				reason: "value must be greater than 0",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	} else {
		err := UpdateCartNumRequestValidationError{
			field:  "Num",
			reason: "value is required and must not be nil.",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpdateCartNumRequestMultiError(errors)
	}

	return nil
}

// UpdateCartNumRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateCartNumRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateCartNumRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateCartNumRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateCartNumRequestMultiError) AllErrors() []error { return m }

// UpdateCartNumRequestValidationError is the validation error returned by
// UpdateCartNumRequest.Validate if the designated constraints aren't met.
type UpdateCartNumRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateCartNumRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateCartNumRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateCartNumRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateCartNumRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateCartNumRequestValidationError) ErrorName() string {
	return "UpdateCartNumRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateCartNumRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateCartNumRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateCartNumRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateCartNumRequestValidationError{}

// Validate checks the field values on UpdateCartNumReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateCartNumReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateCartNumReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateCartNumReplyMultiError, or nil if none found.
func (m *UpdateCartNumReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateCartNumReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Affected

	if len(errors) > 0 {
		return UpdateCartNumReplyMultiError(errors)
	}

	return nil
}

// UpdateCartNumReplyMultiError is an error wrapping multiple validation errors
// returned by UpdateCartNumReply.ValidateAll() if the designated constraints
// aren't met.
type UpdateCartNumReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateCartNumReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateCartNumReplyMultiError) AllErrors() []error { return m }

// UpdateCartNumReplyValidationError is the validation error returned by
// UpdateCartNumReply.Validate if the designated constraints aren't met.
type UpdateCartNumReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateCartNumReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateCartNumReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateCartNumReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateCartNumReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateCartNumReplyValidationError) ErrorName() string {
	return "UpdateCartNumReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateCartNumReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateCartNumReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateCartNumReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateCartNumReplyValidationError{}

// Validate checks the field values on RemoveCartItemsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RemoveCartItemsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RemoveCartItemsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RemoveCartItemsRequestMultiError, or nil if none found.
func (m *RemoveCartItemsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RemoveCartItemsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if wrapper := m.GetUserId(); wrapper != nil {

		if wrapper.GetValue() <= 0 {
			err := RemoveCartItemsRequestValidationError{
				field:  "UserId",
				reason: "value must be greater than 0",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	} else {
		err := RemoveCartItemsRequestValidationError{
			field:  "UserId",
			reason: "value is required and must not be nil.",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetIds()) < 1 {
		err := RemoveCartItemsRequestValidationError{
			field:  "Ids",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RemoveCartItemsRequestMultiError(errors)
	}

	return nil
}

// RemoveCartItemsRequestMultiError is an error wrapping multiple validation
// errors returned by RemoveCartItemsRequest.ValidateAll() if the designated
// constraints aren't met.
type RemoveCartItemsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemoveCartItemsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemoveCartItemsRequestMultiError) AllErrors() []error { return m }

// RemoveCartItemsRequestValidationError is the validation error returned by
// RemoveCartItemsRequest.Validate if the designated constraints aren't met.
type RemoveCartItemsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveCartItemsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveCartItemsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveCartItemsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveCartItemsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveCartItemsRequestValidationError) ErrorName() string {
	return "RemoveCartItemsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveCartItemsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveCartItemsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveCartItemsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveCartItemsRequestValidationError{}

// Validate checks the field values on RemoveCartItemsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RemoveCartItemsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RemoveCartItemsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RemoveCartItemsReplyMultiError, or nil if none found.
func (m *RemoveCartItemsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *RemoveCartItemsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Affected

	if len(errors) > 0 {
		return RemoveCartItemsReplyMultiError(errors)
	}

	return nil
}

// RemoveCartItemsReplyMultiError is an error wrapping multiple validation
// errors returned by RemoveCartItemsReply.ValidateAll() if the designated
// constraints aren't met.
type RemoveCartItemsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemoveCartItemsReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemoveCartItemsReplyMultiError) AllErrors() []error { return m }

// RemoveCartItemsReplyValidationError is the validation error returned by
// RemoveCartItemsReply.Validate if the designated constraints aren't met.
type RemoveCartItemsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveCartItemsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveCartItemsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveCartItemsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveCartItemsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveCartItemsReplyValidationError) ErrorName() string {
	return "RemoveCartItemsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveCartItemsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveCartItemsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveCartItemsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveCartItemsReplyValidationError{}

// Validate checks the field values on GetCartsByUserIdReply_CartItem with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCartsByUserIdReply_CartItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCartsByUserIdReply_CartItem with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetCartsByUserIdReply_CartItemMultiError, or nil if none found.
func (m *GetCartsByUserIdReply_CartItem) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCartsByUserIdReply_CartItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CartId

	// no validation rules for GoodsSkuId

	// no validation rules for GoodsId

	// no validation rules for Num

	// no validation rules for GoodsSkuDesc

	if len(errors) > 0 {
		return GetCartsByUserIdReply_CartItemMultiError(errors)
	}

	return nil
}

// GetCartsByUserIdReply_CartItemMultiError is an error wrapping multiple
// validation errors returned by GetCartsByUserIdReply_CartItem.ValidateAll()
// if the designated constraints aren't met.
type GetCartsByUserIdReply_CartItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCartsByUserIdReply_CartItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCartsByUserIdReply_CartItemMultiError) AllErrors() []error { return m }

// GetCartsByUserIdReply_CartItemValidationError is the validation error
// returned by GetCartsByUserIdReply_CartItem.Validate if the designated
// constraints aren't met.
type GetCartsByUserIdReply_CartItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCartsByUserIdReply_CartItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCartsByUserIdReply_CartItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCartsByUserIdReply_CartItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCartsByUserIdReply_CartItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCartsByUserIdReply_CartItemValidationError) ErrorName() string {
	return "GetCartsByUserIdReply_CartItemValidationError"
}

// Error satisfies the builtin error interface
func (e GetCartsByUserIdReply_CartItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCartsByUserIdReply_CartItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCartsByUserIdReply_CartItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCartsByUserIdReply_CartItemValidationError{}
