// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	biz2 "imperialPalaceMall/app/mall/internal/biz"
	"imperialPalaceMall/app/mall/internal/conf"
	data2 "imperialPalaceMall/app/mall/internal/data"
	"imperialPalaceMall/app/mall/internal/server"
	service2 "imperialPalaceMall/app/mall/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data2.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	categoryRepo := data2.NewCategoryRepo(dataData, logger)
	categoryUsecase := biz2.NewCategoryUsecase(categoryRepo, logger)
	categoryServiceService := service2.NewCategoryServiceService(categoryUsecase)
	goodsRepo := data2.NewGoodsRepo(dataData, logger)
	goodsUsecase := biz2.NewGoodsUsecase(goodsRepo, logger)
	goodsServiceService := service2.NewGoodsServiceService(goodsUsecase)
	httpServer := server.NewHTTPServer(confServer, categoryServiceService, goodsServiceService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
