server:
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  database:
    driver: postgres
    addr: 127.0.0.1
    dbname: userdb
    user: malluser
    password: ${DB_PASS}
    port: 5432
#    source: ${data.database.driver}://${DB_SOURCE}?sslmode=disable
  redis:
    addr: 127.0.0.1:6379
    dial_timeout: 1s
    read_timeout: 0.4s
    write_timeout: 0.6s
  weixin:
    addr: "https://api.weixin.qq.com"
    appid: wx4e95273b19b663cf
    secret: ${APP_SECRET}
    grant_type: authorization_code
